name: Release

on:
  push:
    branches:
      - main

jobs:
  release-libs-features:
    name: Release Libs and Features
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.create-release-pull-request-or-publish.outputs.published }}
      publishedPackages: ${{ steps.create-release-pull-request-or-publish.outputs.publishedPackages }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - id: enable-corepack
        name: Enable Corepack
        run: corepack enable

      - id: use-node-js
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"

      - id: install-dependencies
        name: Install dependencies
        run: yarn --immutable

      - id: get-publishable-packages
        name: Get publishable packages
        run: |
          # Use a temporary file in the current directory
          TEMP_FILE="temp-changeset-status.json"
          
          # Generate the JSON output
          yarn changeset status --output=${TEMP_FILE}
          
          # Extract package names from the JSON file and filter out private packages
          PACKAGES=$(cat ${TEMP_FILE} | jq -r '.releases[].name' | while read pkg; do
            # Check if package is private
            is_private=$(cat $(find . -path "*/${pkg}/package.json" | head -n 1) | jq -r '.private // false')
            if [ "$is_private" != "true" ]; then
              echo "$pkg"
            fi
          done | tr '\n' ' ')
          
          # Clean up
          rm ${TEMP_FILE}
          
          echo "packages=${PACKAGES}" >> $GITHUB_OUTPUT

      - id: create-release-pull-request-or-publish
        name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn build:all -p ${{ steps.get-publishable-packages.outputs.packages }} && yarn changeset publish
          commit: "chore: publish new release"
          title: "chore: publish new release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - id: get-current-branch
        name: Get current branch
        run: echo "name=$(git branch --show-current)" >> $GITHUB_OUTPUT

      - id: update-lock-file
        name: Update lock file
        if: steps.get-current-branch.outputs.name == 'changeset-release/main'
        run: yarn --mode=update-lockfile

      - id: commit-lock-file
        name: Commit lock file
        if: steps.get-current-branch.outputs.name == 'changeset-release/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update lock file"
          branch: changeset-release/main

  release-apps:
    needs: release-libs-features
    name: Release Apps
    runs-on: ubuntu-latest
    if: needs.release-libs-features.outputs.published == 'true'
    strategy:
      matrix:
        include:
          - app: server/auth-api
            package: "@robust-monorepo-yarn-nx-changesets/auth-api"
          - app: client/auth-app
            package: "@robust-monorepo-yarn-nx-changesets/auth-app"
    steps:
      - uses: actions/checkout@v4

      - id: check-if-published
        name: Check if app is in published packages
        run: |
          PUBLISHED_PACKAGES="${{ needs.release-libs-features.outputs.publishedPackages }}"
          PACKAGE_NAME="${{ matrix.package }}"
      
          if echo "$PUBLISHED_PACKAGES" | grep -w "$PACKAGE_NAME"; then
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "published=false" >> $GITHUB_OUTPUT
          fi

      - id: set-up-docker
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: get-app-version
        name: Get the app version from package.json
        run: echo "app-version=$(cat ./apps/${{ matrix.app }}/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - id: build-image
        name: Build image
        if: steps.check-if-published.outputs.published == 'true'
        uses: docker/build-push-action@v4
        with:
          build-contexts: |
            workspace=./
          context: "./apps/${{ matrix.app }}"
          load: true
          push: false
          tags: |
            ${{ matrix.app }}:v${{ steps.get-app-version.outputs.app-version }}
