name: Release

on:
  push:
    branches:
      - main

jobs:
  release-libs-features:
    name: Release Libs and Features
    runs-on: ubuntu-latest
    outputs:
      publishedPackages: ${{ steps.create-release-pull-request-or-publish.outputs.publishedPackages }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - id: enable-corepack
        name: Enable Corepack
        run: corepack enable

      - id: use-node-js
        name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"

      - id: install-dependencies
        name: Install dependencies
        run: yarn --immutable

      - id: build-packages
        name: Build packages
        run: yarn build:affected

      - id: create-release-pull-request-or-publish
        name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn release
          commit: "chore: publish new release"
          title: "chore: publish new release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-apps:
    needs: release-libs-features
    uses: ./.github/workflows/release-apps.yaml
    with:
      publishedPackages: ${{ needs.release-libs-features.outputs.publishedPackages }}
